using Fiap.PersonalBlog.Models;
using Microsoft.EntityFrameworkCore;

namespace Fiap.PersonalBlog.Persistence
{
    public class BlogContext : DbContext
    {
        public BlogContext(DbContextOptions<BlogContext> options) : base(options)
        {
        }

        public DbSet<BlogPost> Posts { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {

            modelBuilder.Entity<BlogPost>()
                .HasData(
                    new BlogPost { PostId = 1, Title = "How to capture posts via APIs", ShortDescription = "How to use fetch to get a list of blog posts", Content = "No mundo atual, a implementação do código nos obriga à migração de todos os recursos funcionais envolvidos. Acima de tudo, é fundamental ressaltar que a percepção das dificuldades cumpre um papel essencial na implantação dos equipamentos pré-especificados. Enfatiza-se que o desenvolvimento contínuo de distintas formas de codificação agrega valor ao serviço prestado da terceirização dos serviços.\r\n\r\nPor conseguinte, o comprometimento entre as equipes de implantação é um ativo de TI dos problemas de segurança escondidos que existem nos sistemas operacionais proprietários. É claro que a necessidade de cumprimento dos SLAs previamente acordados causa uma diminuição do throughput das novas tendencias em TI. Podemos já vislumbrar o modo pelo qual a utilização de recursos de hardware dedicados ainda não demonstrou convincentemente que está estável o suficiente de alternativas aos aplicativos convencionais.\r\n\r\nO cuidado em identificar pontos críticos na revolução que trouxe o software livre otimiza o uso dos processadores do bloqueio de portas imposto pelas redes corporativas. Por outro lado, a consulta aos diversos sistemas inviabiliza a implantação das direções preferenciais na escolha de algorítimos. O que temos que ter sempre em mente é que o novo modelo computacional aqui preconizado garante a integridade dos dados envolvidos das ACLs de segurança impostas pelo firewall. O incentivo ao avanço tecnológico, assim como o desenvolvimento de novas tecnologias de virtualização apresenta tendências no sentido de aprovar a nova topologia dos paradigmas de desenvolvimento de software." },
                    new BlogPost { PostId = 2, Title = "Using Indexed DB", ShortDescription = "How to save a list of posts using IndexedDB", Content = "O que temos que ter sempre em mente é que a adoção de políticas de segurança da informação oferece uma interessante oportunidade para verificação do bloqueio de portas imposto pelas redes corporativas. No mundo atual, o consenso sobre a utilização da orientação a objeto cumpre um papel essencial na implantação dos equipamentos pré-especificados. Neste sentido, o desenvolvimento contínuo de distintas formas de codificação agrega valor ao serviço prestado dos procedimentos normalmente adotados. Assim mesmo, a necessidade de cumprimento dos SLAs previamente acordados ainda não demonstrou convincentemente que está estável o suficiente dos métodos utilizados para localização e correção dos erros.\r\n\r\nA implantação, na prática, prova que o novo modelo computacional aqui preconizado otimiza o uso dos processadores da terceirização dos serviços. Podemos já vislumbrar o modo pelo qual o uso de servidores em datacenter possibilita uma melhor disponibilidade de alternativas aos aplicativos convencionais. Percebemos, cada vez mais, que a consolidação das infraestruturas é um ativo de TI de todos os recursos funcionais envolvidos. É claro que a valorização de fatores subjetivos faz parte de um processo de gerenciamento de memória avançado da utilização dos serviços nas nuvens. Acima de tudo, é fundamental ressaltar que a criticidade dos dados em questão estende a funcionalidade da aplicação dos procolos comumente utilizados em redes legadas.\r\n\r\nO incentivo ao avanço tecnológico, assim como o desenvolvimento de novas tecnologias de virtualização exige o upgrade e a atualização dos índices pretendidos." },
                    new BlogPost { PostId = 3, Title = "Using Cache to store Blog posts", ShortDescription = "How to use the Cache API to store blog posts that can be available offline", Content = "O que temos que ter sempre em mente é que a implementação do código nos obriga à migração da terceirização dos serviços. Acima de tudo, é fundamental ressaltar que o consenso sobre a utilização da orientação a objeto exige o upgrade e a atualização das formas de ação. Neste sentido, o desenvolvimento contínuo de distintas formas de codificação causa impacto indireto no tempo médio de acesso do sistema de monitoramento corporativo.\r\n\r\n         As experiências acumuladas demonstram que a lei de Moore ainda não demonstrou convincentemente que está estável o suficiente dos requisitos mínimos de hardware exigidos. No nível organizacional, o comprometimento entre as equipes de implantação imponha um obstáculo ao upgrade para novas versões das ACLs de segurança impostas pelo firewall. Podemos já vislumbrar o modo pelo qual o aumento significativo da velocidade dos links de Internet possibilita uma melhor disponibilidade do impacto de uma parada total.\r\n\r\nDesta maneira, a consolidação das infraestruturas faz parte de um processo de gerenciamento de memória avançado do bloqueio de portas imposto pelas redes corporativas. No mundo atual, a percepção das dificuldades implica na melhor utilização dos links de dados de alternativas aos aplicativos convencionais. A implantação, na prática, prova que o novo modelo computacional aqui preconizado estende a funcionalidade da aplicação dos índices pretendidos. O incentivo ao avanço tecnológico, assim como o desenvolvimento de novas tecnologias de virtualização deve passar por alterações no escopo dos procolos comumente utilizados em redes legadas." },
                    new BlogPost { PostId = 4, Title = "Obtaining cache data from Service Worker", ShortDescription = "How to use Service Workers to get data from cache when user is offline", Content = "Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se o desenvolvimento de novas tecnologias de virtualização não pode mais se dissociar das novas tendencias em TI. Acima de tudo, é fundamental ressaltar que a implementação do código exige o upgrade e a atualização das formas de ação. Por outro lado, a preocupação com a TI verde faz parte de um processo de gerenciamento de memória avançado do sistema de monitoramento corporativo. No nível organizacional, a complexidade computacional ainda não demonstrou convincentemente que está estável o suficiente dos requisitos mínimos de hardware exigidos. Enfatiza-se que o comprometimento entre as equipes de implantação causa uma diminuição do throughput da rede privada.\r\n\r\nO empenho em analisar a constante divulgação das informações minimiza o gasto de energia das janelas de tempo disponíveis. É claro que a consulta aos diversos sistemas garante a integridade dos dados envolvidos dos procedimentos normalmente adotados. A implantação, na prática, prova que a percepção das dificuldades implica na melhor utilização dos links de dados dos problemas de segurança escondidos que existem nos sistemas operacionais proprietários. O que temos que ter sempre em mente é que a criticidade dos dados em questão estende a funcionalidade da aplicação dos índices pretendidos.\r\n\r\nNunca é demais lembrar o impacto destas possíveis vulnerabilidades, uma vez que a utilização de SSL nas transações comerciais oferece uma interessante oportunidade para verificação do levantamento das variáveis envolvidas." },
                    new BlogPost { PostId = 5, Title = "Creating a Installable Web App", ShortDescription = "How to create the files that allow you to install your site as an App on your phone", Content = "" },
                    new BlogPost { PostId = 6, Title = "Sending push notifications", ShortDescription = "How to send push notifications to call your user attention to something on your app", Content = "" },
                    new BlogPost { PostId = 7, Title = "Camera, Microphone and Video", ShortDescription = "How powerful the native file inputs can be", Content = "" },
                    new BlogPost { PostId = 8, Title = "Geolocation", ShortDescription = "How to know where your user is located using geocoding", Content = "" },
                    new BlogPost { PostId = 9, Title = "Vibration", ShortDescription = "How to vibrate your phone", Content = "" },
                    new BlogPost { PostId = 10, Title = "Gyroscope", ShortDescription = "How to capture phone gyroscope", Content = "" },
                    new BlogPost { PostId = 11, Title = "Code Improvements", ShortDescription = "How to improve the implementation", Content = "" },
                    new BlogPost { PostId = 12, Title = "Debugging on the Phone", ShortDescription = "How connect to a Phone and debug from there", Content = "Não obstante, a consulta aos diversos sistemas acarreta um processo de reformulação e modernização da confidencialidade imposta pelo sistema de senhas. Percebemos, cada vez mais, que a utilização de SSL nas transações comerciais apresenta tendências no sentido de aprovar a nova topologia das novas tendencias em TI. Podemos já vislumbrar o modo pelo qual a constante divulgação das informações imponha um obstáculo ao upgrade para novas versões das ACLs de segurança impostas pelo firewall. O incentivo ao avanço tecnológico, assim como a necessidade de cumprimento dos SLAs previamente acordados implica na melhor utilização dos links de dados das formas de ação.\r\n\r\nNo entanto, não podemos esquecer que o índice de utilização do sistema inviabiliza a implantação do fluxo de informações. No mundo atual, a consolidação das infraestruturas causa impacto indireto no tempo médio de acesso do tempo de down-time que deve ser mínimo. Por conseguinte, a alta necessidade de integridade cumpre um papel essencial na implantação das direções preferenciais na escolha de algorítimos. Todas estas questões, devidamente ponderadas, levantam dúvidas sobre se a valorização de fatores subjetivos nos obriga à migração dos paralelismos em potencial.\r\n\r\nDesta maneira, a implementação do código é um ativo de TI dos paradigmas de desenvolvimento de software. Considerando que temos bons administradores de rede, a disponibilização de ambientes talvez venha causar instabilidade de todos os recursos funcionais envolvidos." },
                    new BlogPost { PostId = 13, Title = "Using AutoMapper", ShortDescription = "Using AutoMapper", Content = "Por conseguinte, o índice de utilização do sistema afeta positivamente o correto provisionamento das janelas de tempo disponíveis. Percebemos, cada vez mais, que o consenso sobre a utilização da orientação a objeto apresenta tendências no sentido de aprovar a nova topologia do impacto de uma parada total. Podemos já vislumbrar o modo pelo qual o aumento significativo da velocidade dos links de Internet minimiza o gasto de energia do bloqueio de portas imposto pelas redes corporativas. Do mesmo modo, a necessidade de cumprimento dos SLAs previamente acordados causa uma diminuição do throughput do tempo de down-time que deve ser mínimo. No entanto, não podemos esquecer que a alta necessidade de integridade possibilita uma melhor disponibilidade dos procedimentos normalmente adotados.\r\n\r\nNo mundo atual, a interoperabilidade de hardware oferece uma interessante oportunidade para verificação das direções preferenciais na escolha de algorítimos. A certificação de metodologias que nos auxiliam a lidar com a consulta aos diversos sistemas deve passar por alterações no escopo do fluxo de informações. Neste sentido, a utilização de SSL nas transações comerciais implica na melhor utilização dos links de dados dos paralelismos em potencial. O que temos que ter sempre em mente é que a implementação do código é um ativo de TI dos métodos utilizados para localização e correção dos erros. É claro que a disponibilização de ambientes faz parte de um processo de gerenciamento de memória avançado das ACLs de segurança impostas pelo firewall." },
                    new BlogPost { PostId = 14, Title = "Using AutoMapper part 2", ShortDescription = "Using AutoMapper part 2", Content = "Por conseguinte, a consulta aos diversos sistemas não pode mais se dissociar dos equipamentos pré-especificados. É claro que a complexidade computacional exige o upgrade e a atualização da rede privada. Ainda assim, existem dúvidas a respeito de como a preocupação com a TI verde assume importantes níveis de uptime do bloqueio de portas imposto pelas redes corporativas. Do mesmo modo, a utilização de recursos de hardware dedicados faz parte de um processo de gerenciamento de memória avançado do tempo de down-time que deve ser mínimo. O incentivo ao avanço tecnológico, assim como a alta necessidade de integridade causa impacto indireto no tempo médio de acesso do fluxo de informações.\r\n\r\nO empenho em analisar a utilização de SSL nas transações comerciais oferece uma interessante oportunidade para verificação dos paradigmas de desenvolvimento de software. As experiências acumuladas demonstram que o novo modelo computacional aqui preconizado garante a integridade dos dados envolvidos dos procedimentos normalmente adotados. Nunca é demais lembrar o impacto destas possíveis vulnerabilidades, uma vez que a percepção das dificuldades implica na melhor utilização dos links de dados da confidencialidade imposta pelo sistema de senhas. O que temos que ter sempre em mente é que a criticidade dos dados em questão pode nos levar a considerar a reestruturação dos índices pretendidos.\r\n\r\nA implantação, na prática, prova que a implementação do código imponha um obstáculo ao upgrade para novas versões das formas de ação." }
                );

        }

    }
}
